rem 共通メッセージ
set TDENC_NAME=まつおかれんこ
set TDENC_NAME2=（つんでれんこ改造版）
set PROCESS_ANNOUNCE=処理中！熱くなれよ！！（CPU的な意味で
set MOVIE_FILE_ANNOUNCE=映像ファイル：
set AUDIO_FILE_ANNOUNCE=音声ファイル：
set PAUSE_MESSAGE1=（夏蓮根を終了する造！！Enterキーを押せ！！）
set PAUSE_MESSAGE2=Enterキーを押して、生き生きする造！！
set HORIZON=------------------------------------------------------------------------------
set HORIZON_B===============================================================================
set USED_SOFTWARE=動画書き出しに使用したソフト：（例：WMM、NiVE）

rem 【ここに動画をD＆D】.batのメッセージ
set TDENC_TITLE=ああ！？ちゃんと・・・言えよ！！！
set PRESET_ALERT=プリセットのバージョンが古いZOU！！
set USER_SETTING1=user_setting.batのバージョンが古いZOU！！
set USER_SETTING2=user_setting.batを自動更新するか？（y/n）
set USER_SETTING3=を更新するZOU！。これまでの設定ファイルは、
set USER_SETTING4=にリネームしとくZOU！！
set PRESET_ALERT2=手動更新する場合はUSER_VERSIONの修正も忘れるなよ！！
set PRESET_ALERT3=（旧バージョンの設定は無視するZOU！！）
set DOUBLECLICK_ALERT1=このファイルをダブルクリックしても何の意味もないよねぇ～
set DOUBLECLICK_ALERT2=つんでれんこまとめwikiの使い方をちゃんと・・・読めよ！！
set FILENAME_ERROR1=あ！？ファイル名かフォルダ名の中にちゃんと扱えない特殊な文字があるZOU！！
set FILENAME_ERROR2=List2で文字化けしてるファイル名かフォルダ名を変えて、もう一回チャレンジ！！
set FILENAME_ERROR3=上で切れている後の文字が問題だ！！修正して、もう一回チャレンジ！！
set UNITE_AVI_ANNOUNCE1=分割AVI連結えんこもーど
set UNITE_AVI_ANNOUNCE2=※インタレ解除・フルレンジ機能などは無効
set ONE_MOVIE_ANNOUNCE=通常えんこもーど
set SEQUENCE_ANNOUNCE=連続えんこもーど
set SEQUENCE_ANNOUNCE2=連続テストえんこも～ど
set MOVIE_INFO_ERROR1=動画解析に失敗・・・あはぁ～ん・・・
set MOVIE_INFO_ERROR2=ユーザー名、フォルダ名、ファイル名に「＝」か全角のスペースが使われてる可能性がある！！
set MOVIE_INFO_ERROR3=　　対処法１：ファイル名から全角のスペースを削除する
set MOVIE_INFO_ERROR4=　　対処法２：一旦動画をドライブ（Cドライブ等）直下に移動する
set SEQUENCE_END1=「お」「わ」「り」！！！ありがとう！！！！
set SEQUENCE_END2=どのファイルがどのMP4かきちんとメモしてからウィンドウを閉じろよ！！
set SEQUENCE_END3=今度からはもっと生き生きする造！！！！
set SEQUENCE_END4=個のエンコードできない動画があったぞ！！
set SEQUENCE_END5=そもそも、このパソコンで正しく再生できるのか？必要なコーデックはインストールしたか？
set MUX_ANNOUNCE=MUXえんこも～ど
set MUX_ALERT1=.nvvファイルは対応してないZOU！！
set MUX_ALERT2=DirectShow出力でAVIに書き出してから使えよ！
set SWF_ALERT=swfファイルはサポート対象外ＤＡ！
set SWF_ALERT2=この2つのサイトを参考に、aviに変換してくれ！！
set NVV_ALERT=.nvvファイルは対応してないZOU！！DirectShow出力でAVIに書き出してから使えよ！
set VIDEO_ENC_ERROR=映像のエンコードに失敗・・・あはぁ～ん
set AVS_ERROR1=Avisynthのレジストリ登録に失敗・・・あはぁ～ん
set AVS_ERROR2=Avisynthを別途インストールしてからもう一度使ってみたらいいぞ！！！
set AVS_ERROR3=（Avisynth_258.exe＜http://sorceforge.net/projects/avisynth2/＞を手動インストールしてから使ってみろ！！！）
set BRACKET_ERROR1=動画のファイル名かパスに半角の"("や")"が含まれていると、エンコードできないだ！リネームしてくれ！
set PROJECTFILE_ERROR1=おい！！これ動画ファイルじゃなくてプロジェクトファイルじゃないか！！
set PROJECTFILE_ERROR2=Windowsムービーメーカーで「ムービーの発行」をしてwmvファイルにしてもう一回チャレンジ！！
set PROJECTFILE_ERROR3=Windows　Liveムービーメーカーで「ムービーの保存」をしてwmvファイルにしてもう一回チャレンジ！！
set PROJECTFILE_ERROR4=AviUtlで「AVI出力」をしてaviファイルにしてもう一回チャレンジ！！
set PROJECTFILE_ERROR5=ニコニコムービーメーカーのファイル→動画をアップロードで直接投稿してみろ！！
set PATH_ERROR1=なんだ？PATHの設定がおかしくなってないか？
set PATH_ERROR2=次のページを参考に修正してみたらどうだ？
set ANTIVIRUS_ERROR1=なんだ？アンチウイルスソフトが必要なファイルを消しているんじゃねーか？
set ANTIVIRUS_ERROR2=toolフォルダに7z.exe、7z.dll、curl.exeが無かったら、アンチウイルスソフトの設定を変更しろ！！
set ANTIVIRUS_ERROR3=その後、zipを解凍するところから、再チャレンジ！！
set UNZIP_ERROR1=zipの解凍がおかしくないか？解凍方法を変更してみろ！！
set DELTEMP1=なんだ？前にエンコに失敗した時の一時ファイルがたくさん残っているんじゃねーか？
set DELTEMP2=同時に他にエンコしてないなら、削除してしまうがいいか？（y/n）
set ANTIVIRUS_ERROR4=アンチウィルスソフトが俺の妨害をしているZOU！！
set ANTIVIRUS_ERROR5=avs2pipemod、curl、MediaInfo、neroAacEnc、x264とかの実行を許可するように設定変更してくれ！！
set FILE_DROP1=まずは、動画ファイルをこのウィンドウにドロップだ！！
set FILE_DROP2=次！！音声ファイル！！カモーン！！
set FILE_DROP3=（さっきの動画ファイルの音声を使う場合はもう一度動画をドロップだ！！）
set FILE_DROP4=ドロップしたら、Enterキーを一回だけ押してくれ！！
set FILE_DROP5=空白や記号が含まれていたりして、もし、うまく動かなかったら、直して再チャレンジ！！
set FILENAME_ERROR_MP4=こんなファイル名つけるんじゃねーよ！！MP4

rem avs.bat、cat.bat、movie.bat、mux.batのメッセージ
set ANALYZE_ANNOUNCE=動画解析中！竹になろうよ
set ANALYZE_END=動画解析完了！！お米食べろ！！！
set ANALYZE_ERROR1=動画の解析に失敗・・・あはぁ～ん
set ANALYZE_ERROR2=での動画の解析に失敗・・・あはぁ～ん
set ANALYZE_ERROR3=まだまだ！！もう一回チャレンジ！！
set ANALYZE_ERROR4=まだまだ終わらない造！！動画フォーマットを変えて、さらにもう一回チャレンジ！！！！（y/n）
set DECODE_ERROR1=動画のデコードに失敗した・・・あはぁ～ん
set DECODE_ERROR2=インデックス処理をしてもう一度チャレンジするから覚悟しとけ！！
set DECODE_ERROR3=正常にデコードできなかった・・・あはぁ～ん
set DECODE_ERROR4=ダメダメダメダメそこであきらめたら！Avisynth_258.exe＜http://sorceforge.net/projects/avisynth2/＞を手動インストール！
set DECODE_ERROR5=まだまだ終わらない造！！映像や音声の形式を変えて保存してからもう一度使ってみろ！！
set DECODE_ERROR6=それでもだめだったら・・・あはぁ～ん・・・
set VIDEO_ENC_ANNOUNCE=動画のエンコ作業に突入！
set AVS_END=映像AVS作成完了！
set VIDEO_ENC_END=動画エンコ完了！
set SILENCE_ANNOUNCE=無音ファイルを作成！
set AUDIO_ENC_ANNOUNCE=音声のエンコ作業に突入！
set SKIP_A_ENC_ANNOUNCE=元のAACな音声をそのまま使うことにするZOU！！
set WAV_ANNOUNCE=WAVファイル作成中！！
set MONAURAL=モノラル
set STEREO=ステレオ
set BITRATE_OVER1=元の動画の映像ビットレート
set BITRATE_OVER2=エンコ後の映像ビットレート
set BITRATE_OVER3=元の動画の映像をそのまま使うことにするZOU！！
set BITRATE_OVER4=おしい！！あとちょっとでエコ回避できる！！もう一回チャレンジ！！
set AMV_INSTALL1=おい！！この動画で使われているAMVビデオコーデックが、インストールされてないぞ！！
set AMV_INSTALL2=AMVコーデックの配布サイトを開くから、インストールしてから、もう一回チャレンジ！！
set AMV_INSTALL3=（シェアウェアだけど、夏蓮根で使うだけだったら、無料で使えるぞ！！）

rem create_mp4.batのメッセージ
set MP4_ANNOUNCE=MP4作成開始！本気でいく造！！
set MP4_ERROR1=エンコードに失敗した・・・あはぁ～ん
set MP4_ERROR2=あはぁ～ん・・・
set MP4_ERROR3=上に「requested bitrate is too low. estimated minimum is ??? kbps」と書かれていたら
set MP4_ERROR4=音声ビットレートを下げて、映像ビットレートを??? kbps以上にしてもう一回チャレンジ！！
set MP4_SUCCESS=MP4作成完了！！
set SIZE_SUCCESS1=あ！？お前動画ファイルの容量オーバーしてんじゃねぇのか！？
set SIZE_SUCCESS2=そんなわけねぇじゃん！！何の問題も無いよねぇ～
set SIZE_ERROR1=あ！？容量オーバー・・・あはぁ～ん
set SIZE_ERROR2=他のプリセットでもう一回チャレンジ！！
set DERE_MESSAGE1=完成したZOU！！
set DERE_MESSAGE2=また会おう！！
set AUTO_BR_LIMIT_CHANGE1=どうやら、なかなか手強い動画が好みのようだな！！
set AUTO_BR_LIMIT_CHANGE2=次から、1passを試す基準を6分51秒以下に変更するZOU！！
set AUTO_BR_LIMIT_CHANGE3=次から、1passを試す基準を5分28秒以下に変更するZOU！！
set ECONOMY_SUCCESS=エコノミー回避できているZOU！！
set ECONOMY_ERROR=エコノミー回避に失敗した・・・あはぁ～ん

rem initialize.batのメッセージ
set INIT_TITLE=今年の僕のテーマは「本気」
set INIT_ANNOUNCE=起動時の設定

rem m4a_enc.batのメッセージ
set SYNC_ANNOUNCE=音ズレ修正中！
set WAV_END=WAVファイル作成完了！
set M4A_ENC_ANNOUNCE=音声エンコ開始！
set WAV_ERROR=あっ！？音声が読み込めないZOU！！無音ファイルを追加する！！
set M4A_SUCCESS=音声エンコ完了！
set SAMPLERATE_ALERT=おい！サンプリングレートが高すぎるぞ！！下げておくからな！！
set AUDIO_BITRATE_ERROR1=音声エンコに失敗した・・・あはぁ～ん
set AUDIO_BITRATE_ERROR2=方法を変えてもう一回チャレンジ！！待ってろ！！

rem setting_question.batのメッセージ
set QUESTION_START1=設定決めたい？設定決めたい！？すぐやっちゃうから！！
set QUESTION_START2=どんな設定にするんだ？
set QUESTION_START3=（今回の設定を保存したいなら、質問の答え　半角スペース　sと入力だ！！）
set QUESTION_START4=（どう答えれば？という時は、aを入力DA！俺に任せておけ！！）
set PRESET_START1=プリセット、選ばせていただくぜ！（l～x）
set PRESET_START2=（よく分からない場合はとりあえずaにしよう）
set PRESET_LIST0=自動設定モード（エンコードに慣れていない人向けプリセット）
set PRESET_LIST1=アニメ・アイマス・MMDなど　速度重視（or 低スペックPC用）
set PRESET_LIST2=アニメ・アイマス・MMDなど　バランス（エンコ速度・画質両立）
set PRESET_LIST3=アニメ・アイマス・MMDなど　画質重視（or 高スペックPC用）
set PRESET_LIST4=実写・PCゲームなど　速度重視（or 低スペックPC用）
set PRESET_LIST5=実写・PCゲームなど　バランス（エンコ速度・画質両立）
set PRESET_LIST6=実写・PCゲームなど　画質重視（or 高スペックPC用）
set PRESET_LIST7=歌ってみたカテゴリなど（音声エンコのみ、高速）
set PRESET_LIST8=ユーザー定義プリセット（カスタマイズ用。デフォでは激重（≠超高画質））
set PRESET_LIST9=YouTube用（リサイズなし＆大容量、高画質にしたい時は1280x720以上で作っておくこと）
set PRESET_LIST10=品質指定（プレアカでの最適ビットレートの見積りに。ファイルサイズ制限無視）
set PRESET_LIST11=音声のみエンコ。動画エンコなし。ファイルサイズ制限なし。高速
set PRESET_MESSAGE1=プリセットsはmp4+wavでしか利用できないぞ！！！
set PRESET_MESSAGE2=（このままやると%DEFAULT_SIZE_PREMIUM%MBを越えるから、ニコ動には投稿できないぞ！）
set RETURN_MESSAGE1=あっ！？ちゃんと・・・言えよ！！！！
set PREMIUM_START1=プレミアム会員？（y/n）
set PREMIUM_START2=（運営に貢いでる人はy、一般会員の人はn）
set PREMIUM_START3=YouTubeのアップロード上限解除の設定は済ませてるか？（y/n）
set PREMIUM_START4=（よくわからない場合はnを選べ！！）
set PREMIUM_START5=どのくらいのビットレートにすればいいか目安を知りたいなら
set PREMIUM_START6=（よくわからないならmを選べ！！）
set PREMIUM_START7=プレミアム会員ならファイルサイズに問題がなければ、そのまま投稿してもいい！！
set PREMIUM_START8=（どうしてもしたいだったら、CRFの値を数字で入力すれば指定できるZOU！！）
set CRF_LIST1=軽さ重視
set CRF_LIST2=バランス
set CRF_LIST3=画質重視
set YOUTUBE_SIZE1=このぐらいのファイルサイズなら、そのまま投稿してもいいんじゃないか！！
set YOUTUBE_SIZE2=俺がエンコしないほうがきれいになるが、それでもエンコするか？（y/n）
set YOUTUBE_ERROR1=上限の解除をしていない場合、動画の長さは15分までだZOU！！
set YOUTUBE_ERROR2=動画を短く分割するか、上限解除の設定をしてくれ！！
set ECONOMY_START1=エコ回避するか？（y/N）
set ECONOMY_START2=高画質をお望みならnだ
set ECONOMY_START3=（エコ回避すると、低画質になるかもしれないが）
set ECONOMY_START4=（一般会員が混雑時間帯に試聴した時の画質・音質劣化を回避できるZOU！！）
set ECONOMY_START5=（主に音を聴いてもらいたい場合以外は、nがオススメDA！！！）
set BITRATE_START1=目標ビットレート（音声＋映像）はいくらだ？（単位はkbps、入力例：1500）
set BITRATE_START2=※今回の動画で可能な限界ビットレート（音声＋映像）は
set BITRATE_START3=（高いほど高画質だが、再生する時重いぞ！覚悟はいいか！）
set BITRATE_START4=（高くても1000～2000kbpsくらいでいいんじゃないか）
set BITRATE_START5=目標ファイルサイズ
set BITRATE_START6=MB → 目標ビットレート
set BITRATE_START7=（aならおまかせ。0なら最大ビットレートでエンコするぞ！！）
set BR_MODE_START1=先に品質基準（crf）エンコを試してみるか？（y/n,CRF数値）
set BR_MODE_START2=※品質基準エンコを使うことで、適切なビットレートに調整が可能
set BR_MODE_START3=　ビットレートが過剰だったら、画質は変わらないのに重くなるだけだぞ！！
set BR_MODE_START4=　ビットレートが指定した値をオーバーした場合は、自動で無効に切り替わり
set BR_MODE_START5=　自動でビットレート基準エンコードでやり直すぞ！！
set BR_MODE_START6=（よくわからないならyを選んでおけ！！）
set RETURN_MESSAGE2=おい！きちんと数字（だけ）を入力しろよ！
set RETURN_MESSAGE3=ビットレートが高すぎる・・・あはぁ～ん
set RETURN_MESSAGE4=ちゃんとビットレートの限界値より低く設定して！
set DECODE_START1=再生負荷を軽くする？（y/n）
set DECODE_START2=（プレアカエンコで動画がカクつく時はyにするとちょっとだけ改善）
set DECODE_START3=（高ビットレートや高解像度はyがお勧め）
set DECODE_START4=（一般アカ用やエコ回避用の時にｙにすると画質が極端に落ちる場合あり）
set DEINT_START1=インターレース解除するか？（a/y/n）
set DEINT_START2=（aは必要かどうか自動判定、yは強制的にする、nは強制的にしない）
set DEINT_START3=（dはfpsを2倍にしつつ、強制的に解除。bはdにするかnにするか自動判定）
set DEINT_START4=（よくわからない場合は、aを選んでおけ！！）
set RESIZE_START1=リサイズは？（入力例：y、n、768:432）
set RESIZE_START2=（yは自動、nはリサイズなし、:（半角）で区切って数値入力で直接指定）
set RESIZE_START3=（横のみを指定した時は、アス比を維持するように縦を計算し、リサイズ）
set RESIZE_START4=※高解像度かつ高FPSの場合、動画視聴中にOSを巻き込んで落ちる場合がある！
set RESIZE_START5=　60fpsなどの時はリサイズすることをお勧めするZOU！
set RESIZE_START6=一般会員の解像度の上限を越えているじゃないか！！今回はリサイズなし（n）は選べないZO！！
set RESIZE_START7=（よくわからない場合はとりあえずyを選べばいい）
set AUDIO_START1=音声のビットレートは？（入力例：160）
set AUDIO_START2=（画質重視：32～48、バランス：96～128、音質重視：192～224が目安だ）
set AUDIO_START3=（無音でいいなら0の入力だ！）
set AUDIO_START4=（元動画と同じにしたい時合はaと入力しろ！高すぎたら%AUTO_A_BITRATE%kbpsにするからな！）
set AUDIO_START5=（悪い、エコノミー回避の時や連結したい時はaじゃなくて、数値を入れてくれ。）
set AUDIO_START6=※今回の動画で有効な音声ビットレートの最大値は
set AUDIO_START7=※元の動画と同様にエコ回避する場合の最大値は
set AUDIO_START6=※今回の動画での音声ビットレートの最大値は
set AUDIO_START7=※元の動画と同様にエコ回避する場合の最大値は
set AUDIO_START8=※今回の動画で有効な音声ビットレートの最大値は
set AUDIO_START9=（これ以上に上げても、聴き分けられる耳と視聴環境を持つ人は中々いないZOU！）
set AUDIO_START10=元の音声をエンコなしでそのまま使いたいなら、aだ！
set RETURN_MESSAGE5=おい！音声ビットレートが高すぎるZOU！！
set RETURN_MESSAGE6=きちんと可能最大総ビットレートより低く設定しろよぉえー！！！
set RETURN_MESSAGE7=あぁ！？ちゃんと・・・言えよ！！！
set RETURN_MESSAGE8=この映像ファイルは一般会員だとプリセットs以外を選んでくれ！！
set RETURN_MESSAGE9=プレミアム会員になるか、プリセットs以外を使ってよね！
set RETURN_MESSAGE10=解像度が一般会員の制限よりが高いZOU！！
set RETURN_MESSAGE11=プレミアム会員になるか、上限以下にリサイズをしろよぉえー！！！
set RETURN_MESSAGE12=この映像ファイルはプリセットsだとエコノミー回避上限をオーバーしてるぞ！！
set RETURN_MESSAGE13=エコノミー回避をしないか、プリセットs以外を選んでくれ！！
set SYNC_START1=音ズレ処理をする？（入力例：y、n、-20、30）
set SYNC_START2=（yだとズレを差分から自動計算して音声の冒頭をカット。それが嫌ならnを選択）
set SYNC_START3=（数値入力だと数値分だけ調整。負だとカット、正だと無音追加。単位はミリ秒）
set SYNC_START7=（1秒（s, sec） ＝1000ミリ秒（ms, msec））
set SYNC_START4=（よくわからない場合はとりあえずyを選べばいいと思う）
set SYNC_START5=（neroAacEnc.exeがないから、今回はyは選べないぞ！！）
set SYNC_START6=（今すぐneroAacEncをダウンロードするか？ならdだ！！）
set GAIN_START1=音量調整するか？（入力例：n、5、-5）
set GAIN_START2=（元のままでいいならnと入力だ！！）
set GAIN_START3=（単位dB。5dBでもかなり音量が違うと思うぞ。上げすぎると音割れするから注意だ！！）
set GAIN_START4=（いきなり20dBとかドカンと上げて、再生時に耳を痛めないようにな！！）
set PWCONF_START2=エンコードが終わったらどうしたいんだ？
set PWCONF_LIST1=シャットダウンするぞ！！！
set PWCONF_LIST2=再起動するぞ！！！
set PWCONF_LIST3=ログオフするぞ！！！
set PWCONF_LIST4=スタンバイするぞ！！！
set PWCONF_LIST5=休止するぞ！！！
set PWCONF_LIST6=電源操作設定を取り止るぞ！！！
set CONFIRM_FILENAME=出力ファイル
set CONFIRM_ON=有効
set CONFIRM_OFF=無効
set CONFIRM_PRETYPE=プリセット　　
set CONFIRM_CRFTYPE=CRF モード　　
set CONFIRM_ACCOUNT1=アカウント　　
set CONFIRM_ACCOUNT2=プレミアム
set CONFIRM_ACCOUNT3=一般
set CONFIRM_ACCOUNT4=YouTube（上限解除済み）
set CONFIRM_ACCOUNT5=YouTube（上限あり）
set CONFIRM_PRETYPE=プリセット　　
set CONFIRM_ENCTYPE=エコ回避　　　
set CONFIRM_DECTYPE=低再生負荷　　
set CONFIRM_DEINT1=インタレ解除
set CONFIRM_DEINT2=自動判定（必要ならば解除）→
set CONFIRM_DEINT3=解除する
set CONFIRM_DEINT4=解除不要
set CONFIRM_RESIZE1=リサイズ　　　
set CONFIRM_RESIZE2=拡大
set CONFIRM_RESIZE3=縮小
set CONFIRM_SYNC1=音ズレ修正　　
set CONFIRM_SYNC2=自動調整
set CONFIRM_SYNC3=手動調整
set CONFIRM_GAIN1=音量調整　　　
set CONFIRM_GAIN2=しない
set CONFIRM_VIDEO=映像　　　　　
set CONFIRM_CRF=品質基準エンコ
set CONFIRM_PRESET_S=エンコせず、元のまま
set CONFIRM_BR=ビットレート基準エンコ
set CONFIRM_BITRATE1=ビットレート　
set CONFIRM_BITRATE2=映像
set CONFIRM_BITRATE3=音声
set CONFIRM_BITRATE4=総合
set UNKNOWN=エンコード後に確認
set YTUPLOAD_BITRATE=YouTubeでサーバーエンコードされた後の最大ビットレート（解像度から判定）
set CONFIRM_LAST1=おい！本当にこれでいいんだな！？（y/n）
set CONFIRM_LAST2=大丈夫。くよくよすんなよ・・・Don’t worry. Be happy.
set CONFIRM_LAST3=全部の動画をこの設定でエンコードするなら、aと入力してくれ！！
set CONFIRM_OUTTYPE=出力ファイル
set MUTE_ALERT1=neroAacEnc.exeがインストールされてないぞ！！無音になってしまうがいいんだな！？
set MUTE_ALERT2=今すぐ、neroAacEnc.exeをダウンロードしていいか？（y/n）
set MUTE_ALERT3=QuickTimeがインストールされてないぞ！！無音になってしまうがいいんだな！？
set MUTE_ALERT4=代わりに、neroAacEnc.exeをインストールしていいか？（y/n）
set M2TS_ALERT1=ファイルはエンコ中にクラッシュすることがあるぞ！！
set M2TS_ALERT2=夏蓮根のtool\TEMPフォルダの下に一時ファイルを作って作業するぞ！！
set M2TS_ALERT3=エンコがうまくいったら、一時ファイルは削除しておくからな！！
set MV1_ALERT1=おい！Microsoft Video 1じゃないか！！これじゃ画質下がっちゃうがいいんだな？
set MV1_ALERT2=次回はUt Vodeo Codecか無圧縮AVIあたり使ってを画質アップだ！！
set SIZE_ALERT=おい！元動画の縦横の解像度が4の倍数じゃないじゃないか！！今回、もし失敗したら直して再チャレンジ！！
set SHUT_CONFIRM=エンコードが終わったら、
set PRETYPES1=この動画はエンコがイマイチかも？プリセットsを使わないほうがいいんじゃないか？
set PRETYPES2=この動画はビットレートが高いな！プリセットaとかも試してみろ！！
set PRETYPES3=動画エンコなしで、音声のみエンコするプリセットsも試してみろ！！
set PRETYPES4=元の動画よりビットレートが膨らんでいるZOU！！

rem shut.batのメッセージ
set SHUT_TITLE=おい！エンコードが終わったZOU！
set SHUT_ALERT=120秒後に全てのアプリケーションを終了後シャットダウンする！
set SHUT_CANCEL=（何かキーを押すとキャンセルする！）
set SHUT_CANCEL2=（キャンセルは右上のXを押すこと！）
set CANCEL_MESSAGE=シャットダウンをキャンセルしたZOU！

rem tool_downloader.batのメッセージ
set DOWNLOADER_TITLE=マイナス10℃の中、ツールがトゥルルってがんばってんだよ！！
set DOWNLOADER_ANNOUNCE=ツールをダウンロード・更新するZOU！
set DOWNLOADER_QUESTION1=すべてのツールを全部自動で落とす？（y/n）
set DOWNLOADER_QUESTION2=（自分で手動で落としたい場合はn）
set NERO_LICENSE1=おい！neroAacEnc.exeを使用するにはライセンスに同意が必要DA！
set NERO_LICENSE2=Nero AAC Codecの「エンドユーザー使用許諾条項」を開く！！
set NERO_LICENSE3=読んだ後戻ってこいよ！（読んだ後は閉じてもいいぞ！！）
set NERO_QUESTION=Nero AAC Codecの「エンドユーザー使用許諾条項」に同意する？（y/n）
set DOWNLOADER_MANUAL1=以下のサイトからひとつひとつ落として、Archivesフォルダに全部入れる！できるよ！！
set DOWNLOADER_MANUAL2=全部ダウンロード終わったか？終わったら戻ってこい！！
set DOWNLOADER_END=我慢しなきゃいけないときだってあるんだよ！
set DOWNLOADER_ERROR1=以下のファイルのダウンロードに失敗した・・・
set DOWNLOADER_ERROR2=（理由：サーバ移転、ダウンローダ不具合、ネット切断、等）
set DOWNLOADER_ERROR3=きちんとネットに繋がってるかもう一度チェックしてから再起動しろよ！！
set DOWNLOADER_ERROR4=それでも駄目だったら、悪いけど手動でダウンロードしてね・・・あはぁ～ん
set DOWNLOADED=もうダウンロードしてあるんなら、ちゃんと言えよ！

rem tool_installer.batのメッセージ
set INSTALLER_TITLE=今日の単語はこれ、「ツールを入れる」意味はみんなわかってるよね、こう東から風が（ry
set INSTALLER_ANNOUNCE=neroAacEnc.exeをtoolフォルダに入れるZOU！
set INSTALLER_ANNOUNCE2=neroAacEnc.exeを使うように設定を書き換えとくZOU！！
set INSTALLER_END=ありがとう！終わったZOU！！
set INSTALLED=おい！もうインストールしてあるじゃないか！

rem version_check.batのメッセージ
set VER_CHECK_ERROR=バージョンチェック失敗（回線切断orダウンローダ起動失敗orサーバダウン）
set VER_CHECK_NEW1=あっ！？新しいバージョンが出てるZOU！
set VER_CHECK_NEW2=（アップデートの方法はサイトの「つかいかた」をきちんと読むことDA！）
set VER_CHECK_LOG=更新内容
set UPDATE_QUESTION1=自動アップデートするか？（y/n/s）
set UPDATE_QUESTION2=（このままエンコードを続けるならnを選択しろ！！）
set UPDATE_QUESTION3=（今後もこのバージョンをスキップし続けたいならsを選択だ！！）
set UPDATE_QUESTION4=（アップデート後に一度終了するZOU！もう一回動画をドロップしろよ！！）
set UPDATE_ERROR=アップデート失敗（回線切断orダウンローダ起動失敗orサーバダウン）
set UPDATE_ANNOUNCE1=アップデート開始～♪
set UPDATE_ANNOUNCE2=アップデート完了～♪
set UPDATE_ANNOUNCE3=次！関連ツールのアップデートをして終了するぞ！！

rem update.batのメッセージ
set INIT_ANNOUNCE2=関連ツール自動アップデート

rem x264_enc.batのメッセージ
set OPTION_SUCCESS=x264オプション設定完了！
set X264_ENC_START=動画エンコ開始！
set PASS_ERROR=おい！パス数の設定が間違ってるZOU！
set PASS_ANNOUNCE1=パス数自動設定モード！
set PASS_ANNOUNCE2=１pass目！お米食べろ！！
set PASS_ANNOUNCE3=２pass目！大丈夫かな・・・あはぁ～ん
set PASS_ANNOUNCE4=…おい、失敗したと思ってんじゃないのか！？駄目だと思って諦めてるんじゃないのか！？
set PASS_ANNOUNCE5=駄目だダメだ、諦めちゃだめだ！できる！できる！！絶対に！！出来るんだから！！！！！
set PASS_ANNOUNCE6=３pass目！まだまだ終わらない造！！
set PASS_ANNOUNCE7=強制1passモード！カニが食べれない
set PASS_ANNOUNCE8=強制2passモード！竹になろうよ
set PASS_ANNOUNCE9=強制3passモード！本気になれば、全てが変わる！
set PASS_ANNOUNCE10=CRFモード～♪
set PASS_ANNOUNCE11=駄目だダメだ、諦めちゃだめだ！できる！できる！！絶対に！！出来るんだから！！！！！
set PASS_ANNOUNCE12=４pass目！これで終わらせてやるかな！！
set X264E_ERROR1=正常にエンコードできなかったZOU・・・
set X264E_ERROR2=デコーダを変えてみるか、おまけで他のコーデックのaviに変換してから
set X264E_ERROR3=もう一回チャレンコDA！！

rem FLV4enc.batのメッセージ
set FLV_ANNOUNCE=FLV作成開始！本気でいく造！！
set VP6VFW_ERROR=vp6vfw.dllが見つからないZOU！インストール方法は、読んでください.txtを読んでくれ！！
set ARATE_ERROR1=FLVを作るには、MP3の音声サンプリングレーを44100Hzか22000Hzにしてくれ！！頼むぜ！！
set ARATE_ERROR2=今回のMP3の音声サンプリングレート
set MP3_SIZE_ERROR=MP3のファイルサイズがデカすぎるぞ！！
set NOT_FLV_ANNOUNCE=FLVじゃなくて、MP4を作ることにするぜ！！いいよな！？
set MAKE_FLV_ANNOUNCE=静止画だったら、MP4じゃなくてFLVがお勧めだ！！できる！できる！！
set FLV_SUCCESS=FLV作成完了！！

rem ここにD&Dして動画をチェック.batのメッセージ
set UP_CHECK1=：投稿可
set UP_CHECK2=：投稿不可
set CONFIRM_ACCOUNT11=会員
