rem 共通メッセージ
set TDENC_NAME=夏蓮根
set TDENC_NAME2=（つんでれんこ改造版）
set PROCESS_ANNOUNCE=処理中～♪
set MOVIE_FILE_ANNOUNCE=映像ファイル：
set AUDIO_FILE_ANNOUNCE=音声ファイル：
set PAUSE_MESSAGE1=（夏蓮根を終了します、Enterキーを押してください）
set PAUSE_MESSAGE2=Enterキーを押して下さい
set HORIZON=------------------------------------------------------------------------------
set HORIZON_B===============================================================================
set USED_SOFTWARE=動画書き出しに使用したソフト：（例：WMM、NiVE）

rem 【ここに動画をD＆D】.batのメッセージ
set TDENC_TITLE=エンコード設定
set PRESET_ALERT=プリセットが旧バージョンのため使用できません。
set USER_SETTING1=user_setting.batのバージョンが古いです
set USER_SETTING2=user_setting.batを自動更新しますか？（y/n）
set USER_SETTING3=を更新します。これまでの設定ファイルは、
set USER_SETTING4=にリネームします
set PRESET_ALERT2=手動更新する場合はUSER_VERSIONの修正も忘れないでください
set PRESET_ALERT3=（旧バージョンの設定は無視します）
set DOUBLECLICK_ALERT1=このファイル名の部分にファイルをD＆Dしてください。
set DOUBLECLICK_ALERT2=詳しくはつんでれんこまとめwikiの使い方を参照下さい。
set FILENAME_ERROR1=ファイル名かフォルダ名の中にうまく扱えない特殊な文字があるようです
set FILENAME_ERROR2=List2で文字化けしているファイル名かフォルダ名を変えてください
set FILENAME_ERROR3=上で切れている後の文字が問題です。修正してみてください
set UNITE_AVI_ANNOUNCE1=分割AVI連結えんこも～ど
set UNITE_AVI_ANNOUNCE2=※インタレ解除・フルレンジ機能などは無効
set ONE_MOVIE_ANNOUNCE=通常えんこも～ど
set SEQUENCE_ANNOUNCE=連続えんこも～ど
set SEQUENCE_ANNOUNCE2=連続テストえんこも～ど
set MOVIE_INFO_ERROR1=動画解析に失敗しました
set MOVIE_INFO_ERROR2=ユーザー名、フォルダ名、ファイル名に「＝」か全角のスペースが使われてる可能性があります
set MOVIE_INFO_ERROR3=　　対処法１：ファイル名から全角のスペースを削除する
set MOVIE_INFO_ERROR4=　　対処法２：一旦動画をドライブ（Cドライブ等）直下に移動する
set SEQUENCE_END1=エンコードが終了しました。
set SEQUENCE_END2=エンコードが終了したMP4ファイル名をメモしておいてください。
set SEQUENCE_END3=エンコードが終了しました。お疲れ様でした
set SEQUENCE_END4=個のエンコードできない動画がありました
set SEQUENCE_END5=そもそも、このパソコンで正しく再生できますか？必要なコーデックはインストール済みですか？
set MUX_ANNOUNCE=MUXえんこも～ど
set MUX_ALERT1=.nvvファイルは対応していません
set MUX_ALERT2=DirectShow出力でAVIに書き出してから使ってください
set SWF_ALERT=swfファイルはサポート対象外です。
set SWF_ALERT2=この2つのサイトを参考にaviに変換してください
set NVV_ALERT=nvvファイルはサポート対象外です。DirectShow出力プラグインでAVIにしてから使ってください
set VIDEO_ENC_ERROR=映像のエンコードに失敗しました。
set AVS_ERROR1=Avisynthのレジストリ登録に失敗。申し訳ありません。
set AVS_ERROR2=Avisynthを別途インストールしてからもう一度使って下さい。
set AVS_ERROR3=（Avisynth_258.exe＜http://sorceforge.net/projects/avisynth2/＞を手動インストールしてから使ってみてください）
set BRACKET_ERROR1=動画のファイル名かパスに半角の"("や")"が含まれていると、エンコードできません。リネームしてください
set PROJECTFILE_ERROR1=これは動画ファイルではなくプロジェクトファイルです
set PROJECTFILE_ERROR2=Windowsムービーメーカーで「ムービーの発行」をしてwmvファイルにしてください
set PROJECTFILE_ERROR3=Windows　Liveムービーメーカーで「ムービーの保存」をしてwmvファイルにしてください
set PROJECTFILE_ERROR4=AviUtlで「AVI出力」をしてaviファイルにしてください
set PROJECTFILE_ERROR5=ニコニコムービーメーカーのファイル→動画をアップロードで直接投稿してみてください
set PROJECTFILE_ERROR6=AviUtlの拡張編集にドロップして下さい
set PROJECTFILE_ERROR6=紙芝居クリエーターで、ファイル→ムービーファイルの保存を行って下さい
set PATH_ERROR1=PATHの設定がおかしくなっている可能性があります
set PATH_ERROR2=次のページを参考に修正してみて下さい
set ANTIVIRUS_ERROR1=アンチウイルスソフトが必要なファイルを消している可能性があります
set ANTIVIRUS_ERROR2=toolフォルダに7z.exe、7z.dll、curl.exeが無い場合、アンチウイルスソフトの設定を変更してください
set ANTIVIRUS_ERROR3=その後、もう一度、zipを解凍するところからやり直してください
set UNZIP_ERROR1=zipの解凍がおかしいです。解凍方法を変更してください
set DELTEMP1=以前にエンコに失敗した時に使用した一時ファイルがたくさん残っているようです
set DELTEMP2=同時に他にエンコしていないなら、削除しますが良いですか？（y/n）
set ANTIVIRUS_ERROR4=アンチウィルスソフトがツールの実行を許可していないようです
set ANTIVIRUS_ERROR5=avs2pipemod、curl、MediaInfo、neroAacEnc、x264などの実行を許可するように設定を変更してください
set FILE_DROP1=動画ファイルをこのウィンドウにドロップしてください
set FILE_DROP2=次に音声ファイルをこのウィンドウにドロップしてください
set FILE_DROP3=（さきほどの動画の音声を使う場合はもう一度動画をドロップしてください）
set FILE_DROP4=ドロップしたら、Enterキーを一回だけ押してください
set FILE_DROP5=空白や記号が含まれていたら、うまく動かないかもしれません
set FILENAME_ERROR_MP4=正しく扱かえないファイル名でしたMP4
set FOLDER_ALERT1=ごめんなさい。このフォルダには書き込みが出来ないみたいです
set FOLDER_ALERT2=（Program Files以下など書き込み制限のある場所には、夏蓮根を置かないで下さい）

rem avs.bat、cat.bat、movie.bat、mux.batのメッセージ
set ANALYZE_ANNOUNCE=動画解析中～♪
set ANALYZE_END=動画解析完了～♪
set ANALYZE_ERROR1=動画の解析に失敗しました。
set ANALYZE_ERROR2=での動画の解析に失敗しました。
set ANALYZE_ERROR3=デコーダーを変えて、もう一度解析を行います。
set ANALYZE_ERROR4=動画フォーマットを変えて、もう一度エンコードしてみますか？（y/n）
set DECODE_ERROR1=動画のデコードに失敗しました。
set DECODE_ERROR2=インデックス処理の後再試行しますのでしばらくお待ちください。
set DECODE_ERROR3=正常にデコードできなませんでした。ご不便をおかけして申し訳ありません。
set DECODE_ERROR4=Avisynth_258.exe＜http://sorceforge.net/projects/avisynth2/＞を手動インストールしてから使ってみてください
set DECODE_ERROR5=ダメなら映像や音声の形式を変えて保存してからもう一度使ってみてください
set DECODE_ERROR6=それでもだめだったら・・・ごめんなさい・・・
set VIDEO_ENC_ANNOUNCE=動画のエンコ作業に突入～♪
set AVS_END=映像AVS作成完了～♪
set VIDEO_ENC_END=動画エンコ完了～♪
set SILENCE_ANNOUNCE=無音ファイルを作成～♪
set AUDIO_ENC_ANNOUNCE=音声のエンコ作業に突入～♪
set SKIP_A_ENC_ANNOUNCE=元のAACな音声をそのまま使います
set WAV_ANNOUNCE=WAVファイル作成中～♪
set MONAURAL=モノラル
set STEREO=ステレオ
set BITRATE_OVER1=元の動画の映像ビットレート
set BITRATE_OVER2=エンコ後の映像ビットレート
set BITRATE_OVER3=元の動画の映像をそのまま使うことにします
set BITRATE_OVER4=あと少しでエコ回避できそうなので、音声エンコをやり直します
set AMV_INSTALL1=この動画はAMVビデオコーデックが使われていますが、このPCにはインストールされていません
set AMV_INSTALL2=AMVコーデックの配布サイトを開きますので、インストールしてやり直してください
set AMV_INSTALL3=（シェアウェアですが、夏蓮根で使うだけなら、無料で使えます）

rem create_mp4.batのメッセージ
set MP4_ANNOUNCE=MP4作成開始～♪
set MP4_ERROR1=エンコードに失敗しました。
set MP4_ERROR2=ご不便をおかけして申し訳ありません。
set MP4_ERROR3=上に「requested bitrate is too low. estimated minimum is ??? kbps」と書かれていたら
set MP4_ERROR4=音声ビットレートを下げて、映像ビットレートを??? kbps以上にしてやり直してみてください
set MP4_SUCCESS=MP4作成完了～♪
set SIZE_SUCCESS1=動画ファイルの容量のチェック完了～♪
set SIZE_SUCCESS2=容量オーバーしていません。
set SIZE_ERROR1=容量オーバーしています
set SIZE_ERROR2=他のプリセットでやり直してください
set DERE_MESSAGE1=完成～♪
set DERE_MESSAGE2=出力結果にご満足いただけなかった場合は大変申し訳ございません。
set AUTO_BR_LIMIT_CHANGE1=今回は圧縮しづらい動画でしたので
set AUTO_BR_LIMIT_CHANGE2=次回から、1passを試す基準を6分51秒以下に変更します
set AUTO_BR_LIMIT_CHANGE3=次回から、1passを試す基準を5分28秒以下に変更します
set ECONOMY_SUCCESS=エコノミー回避できています
set ECONOMY_ERROR=エコノミー回避に失敗しています

rem initialize.batのメッセージ
set INIT_TITLE=初期設定
set INIT_ANNOUNCE=起動時の設定

rem m4a_enc.batのメッセージ
set SYNC_ANNOUNCE=音ズレ修正中～♪
set WAV_END=WAVファイル作成完了～♪
set M4A_ENC_ANNOUNCE=音声エンコ開始～♪
set WAV_ERROR=音声が正常に読み込めなかったため無音ファイルを使用します。
set M4A_SUCCESS=音声エンコ完了～♪
set SAMPLERATE_ALERT=サンプリングレートが高すぎるので下げます
set AUDIO_BITRATE_ERROR1=音声エンコがうまく行きませんでした
set AUDIO_BITRATE_ERROR2=方法を変えてもう一度行なってみます

rem setting_question.batのメッセージ
set QUESTION_START1=エンコード設定を行います。
set QUESTION_START2=設定を選んでください。
set QUESTION_START3=（今回の設定を保存したい時は、質問の答え　半角スペース　sと入力してください）
set QUESTION_START4=（どう答えれば？という時は、aを入力してください。オススメ設定にします）
set PRESET_START1=プリセットはどれにしますか？（l～x）
set PRESET_START2=（よく分からない場合はとりあえずaを選べばいいと思います）
set PRESET_LIST0=自動設定モード（エンコードに慣れていない人向けプリセット）
set PRESET_LIST1=アニメ・アイマス・MMDなど　速度重視（or 低スペックPC用）
set PRESET_LIST2=アニメ・アイマス・MMDなど　バランス（エンコ速度・画質両立）
set PRESET_LIST3=アニメ・アイマス・MMDなど　画質重視（or 高スペックPC用）
set PRESET_LIST4=実写・PCゲームなど　速度重視（or 低スペックPC用）
set PRESET_LIST5=実写・PCゲームなど　バランス（エンコ速度・画質両立）
set PRESET_LIST6=実写・PCゲームなど　画質重視（or 高スペックPC用）
set PRESET_LIST7=歌ってみたカテゴリなど（音声エンコのみ、高速）
set PRESET_LIST8=ユーザー定義プリセット（カスタマイズ用。デフォでは激重（≠超高画質））
set PRESET_LIST9=YouTube用（リサイズなし＆大容量、高画質にしたい時は1280x720以上で作っておくこと）
set PRESET_LIST10=品質指定（プレアカでの最適ビットレートの見積りに。ファイルサイズ制限無視）
set PRESET_LIST11=音声のみエンコ。動画エンコなし。ファイルサイズ制限なし。高速
set PRESET_MESSAGE1=プリセットsはmp4+wavでしか利用できません
set PRESET_MESSAGE2=（このままやると%DEFAULT_SIZE_PREMIUM%MBを越えるので、ニコ動には投稿できません）
set RETURN_MESSAGE1=して以外のキーが押されました。もう一度選んでください。
set PREMIUM_START1=プレミアム会員？（y/n）
set PREMIUM_START2=（プレミアム会員の人はy、一般会員の人はnを押してください）
set PREMIUM_START3=YouTubeのアップロード上限解除の設定は済ませていますか？（y/n）
set PREMIUM_START4=（よくわからない場合はnを選んでください）
set PREMIUM_START5=どのくらいのビットレートにすればいいか目安を知りたい時は
set PREMIUM_START6=（よくわからない時はmを選べばいいと思います）
set PREMIUM_START7=プレミアム会員ならファイルサイズに問題がなければ、そのまま投稿できます
set PREMIUM_START8=（どうしてもしたいなら、CRFの値を数字で入力すれば指定できます）
set CRF_LIST1=軽さ重視
set CRF_LIST2=バランス
set CRF_LIST3=画質重視
set YOUTUBE_SIZE1=このぐらいのファイルサイズなら、そのまま投稿しても時間はかからなくありませんか？
set YOUTUBE_SIZE2=エンコしないほうがきれいになると思いますが、それでもエンコしますか？（y/n）
set YOUTUBE_ERROR1=上限の解除をしていない場合、動画の長さは15分までです
set YOUTUBE_ERROR2=動画を短く分割するか、上限解除の設定をしてください
set ECONOMY_START1=エコ回避しますか？（y/N）
set ECONOMY_START2=高画質をお望みならnを
set ECONOMY_START3=（エコ回避すると、低画質になるかもしれないけれど）
set ECONOMY_START4=（一般会員が混雑時間帯に試聴した時の画質・音質劣化を回避できます）
set ECONOMY_START5=（主に音を聴いてもらいたい場合用かも）
set BITRATE_START1=目標ビットレート（音声＋映像）はいくつ？（単位はkbps、入力例：1500）
set BITRATE_START2=※今回の動画で可能な限界ビットレート（音声＋映像）は
set BITRATE_START3=（高くても1000～2000kbpsほどがベストです。）
set BITRATE_START4=（それ以上だとほとんど画質向上せずPCに負担がかかるだけになる場合が多いです。）
set BITRATE_START5=目標ファイルサイズ
set BITRATE_START6=MB → 目標ビットレート
set BR_MODE_START1=先に品質基準（crf）エンコを試してみますか？（y/n,CRF数値）
set BR_MODE_START2=※品質基準エンコを使うことで、適切なビットレートに調整が可能です
set BR_MODE_START3=　ビットレートが過剰だったら、画質は変わらないのに重くなるだけです
set BR_MODE_START4=　ビットレートが指定した値をオーバーした場合は、自動で無効に切り替わり
set BR_MODE_START5=　自動でビットレート基準エンコードでやり直します
set BR_MODE_START6=（よくわからない場合はyを選んでください）
set BITRATE_START7=（aならおまかせ。0なら最大ビットレートでエンコします）
set RETURN_MESSAGE2=半角数字のみ入力してください。
set RETURN_MESSAGE3=ビットレートが高すぎます。
set RETURN_MESSAGE4=ビットレートの限界値より低く設定してください
set RETURN_MESSAGE5=音声ビットレートが高すぎます。
set RETURN_MESSAGE6=可能最大総ビットレートより低く設定してください
set RETURN_MESSAGE7=無効なキーが押されました
set RETURN_MESSAGE8=この映像ファイルは一般会員ではプリセットsを使えません
set RETURN_MESSAGE9=プレミアム会員になるか、プリセットs以外を使ってください
set RETURN_MESSAGE10=解像度が一般会員の制限より高いです
set RETURN_MESSAGE11=プレミアム会員になるか、上限以下にリサイズをしてください
set RETURN_MESSAGE12=この映像ファイルはプリセットsだとエコノミー回避が出来ません
set RETURN_MESSAGE13=エコノミー回避をあきらめるか、プリセットs以外を使ってください
set DECODE_START1=再生負荷を軽くしますか？（y/n）
set DECODE_START2=（プレアカエンコで動画がカクつく時はyにするとちょっとだけ改善）
set DECODE_START3=（高ビットレートや高解像度はyがお勧め）
set DECODE_START4=（一般アカ用やエコ回避用の時にｙにすると画質が極端に落ちる場合あり）
set DEINT_START1=インターレース解除しますか？（a/y/n）
set DEINT_START2=（aは必要かどうか自動判定、yは強制的にする、nは強制的にしない）
set DEINT_START3=（dはfpsを2倍にしつつ、強制的に解除。bはdにするかnにするか自動判定）
set DEINT_START4=（よくわからない場合は、aを選んでください）
set RESIZE_START1=リサイズは？（入力例：y、n、768:432、640）
set RESIZE_START2=（yは自動、nはリサイズなし、:（半角）で区切って数値入力で直接指定）
set RESIZE_START3=（横のみを指定した時は、アス比を維持するように縦を計算し、リサイズします）
set RESIZE_START4=※高解像度かつ高FPSの場合、動画視聴中にOSを巻き込んで落ちる場合があります。
set RESIZE_START5=　60fpsなどの時はリサイズすることをお勧めします
set RESIZE_START6=一般会員の解像度の上限を越えているので、今回はリサイズなし（n）は選べません
set RESIZE_START7=（よくわからない場合はとりあえずyを選んでください）
set AUDIO_START1=音声のビットレートは？（入力例：160）
set AUDIO_START2=（画質重視：32～48、バランス：96～128、音質重視：192～224が目安かな）
set AUDIO_START3=（無音でいいなら0と入力してください）
set AUDIO_START4=（元動画と同じにしたい場合はaと入力してください。高すぎる場合は%AUTO_A_BITRATE%kbpsになります。）
set AUDIO_START5=（ただし、エコノミー回避の場合や連結したい場合は、aを選択できません。数値を入力してください。）
set AUDIO_START6=※今回の動画での音声ビットレートの最大値は
set AUDIO_START7=※元の動画と同様にエコ回避する場合の最大値は
set AUDIO_START8=※今回の動画で有効な音声ビットレートの最大値は
set AUDIO_START9=（これ以上に上げても、聴き分けられる耳と視聴環境を持つ人は中々いません）
set AUDIO_START10=元の音声をエンコなしでそのまま使いたいなら、aと入力してください。
set SYNC_START1=音ズレ処理をする？（入力例：y、n、-20、30）
set SYNC_START2=（yだとズレを差分から自動計算して音声の冒頭をカット。それが嫌ならnを選択）
set SYNC_START3=（数値入力だと数値分だけ調整。負だとカット、正だと無音追加。単位はミリ秒）
set SYNC_START7=（1秒（s, sec） ＝1000ミリ秒（ms, msec））
set SYNC_START4=（よくわからない場合はとりあえずyを選べばいい）
set SYNC_START5=（neroAacEnc.exeがないから、今回はyは選べません）
set SYNC_START6=（今すぐneroAacEncをダウンロードするなら、dを入力）
set GAIN_START1=音量調整しますか？（入力例：n、5、-5）
set GAIN_START2=（元のままでいいならnと入力してください）
set GAIN_START3=（単位dB。5dBでもかなり音量が違うと思います。上げすぎると音割れすることがあります）
set GAIN_START4=（いきなり20dBとか大きく上げて、再生時に耳を痛めないように注意してください。）
set PWCONF_START2=どんな電源操作をしますか？
set PWCONF_LIST1=シャットダウンします
set PWCONF_LIST2=再起動します
set PWCONF_LIST3=ログオフします
set PWCONF_LIST4=スタンバイします
set PWCONF_LIST5=休止します
set PWCONF_LIST6=電源操作設定を取り止めます
set CONFIRM_FILENAME=出力ファイル
set CONFIRM_ON=有効
set CONFIRM_OFF=無効
set CONFIRM_PRETYPE=プリセット　　
set CONFIRM_CRFTYPE=CRF モード　　
set CONFIRM_ACCOUNT1=アカウント　　
set CONFIRM_ACCOUNT2=プレミアム
set CONFIRM_ACCOUNT3=一般
set CONFIRM_ACCOUNT4=YouTube（上限解除済み）
set CONFIRM_ACCOUNT5=YouTube（上限あり）
set CONFIRM_PRETYPE=プリセット　　
set CONFIRM_ENCTYPE=エコ回避　　　
set CONFIRM_DECTYPE=低再生負荷　　
set CONFIRM_DEINT1=インタレ解除
set CONFIRM_DEINT2=自動判定（必要ならば解除）→
set CONFIRM_DEINT3=解除する
set CONFIRM_DEINT4=解除不要
set CONFIRM_RESIZE1=リサイズ　　　
set CONFIRM_RESIZE2=拡大
set CONFIRM_RESIZE3=縮小
set CONFIRM_SYNC1=音ズレ修正　　
set CONFIRM_SYNC2=自動調整
set CONFIRM_SYNC3=手動調整
set CONFIRM_GAIN1=音量調整　　　
set CONFIRM_GAIN2=しない
set CONFIRM_VIDEO=映像　　　　　
set CONFIRM_CRF=品質基準エンコ
set CONFIRM_BR=ビットレート基準エンコ
set CONFIRM_PRESET_S=エンコせず、元のまま
set CONFIRM_BITRATE1=ビットレート　
set CONFIRM_BITRATE2=映像
set CONFIRM_BITRATE3=音声
set CONFIRM_BITRATE4=総合
set UNKNOWN=エンコード後に確認
set YTUPLOAD_BITRATE=YouTubeでサーバーエンコードされた後の最大ビットレート（解像度から判定）
set CONFIRM_LAST1=よろしいですか？（y/n）
set CONFIRM_LAST2=設定をしなおします。
set CONFIRM_LAST3=全部の動画をこの設定でエンコードするなら、aと入力してください
set CONFIRM_OUTTYPE=出力ファイル
set MUTE_ALERT1=neroAacEnc.exeがインストールされていないため、無音になります
set MUTE_ALERT2=今すぐ、neroAacEnc.exeをダウンロードしますか？（y/n）
set MUTE_ALERT3=QuickTimeがインストールされていないため、無音になります
set MUTE_ALERT4=代わりに、neroAacEnc.exeをインストールしますか？（y/n）
set M2TS_ALERT1=ファイルへの対応は不完全のため、うまくエンコードできないことがあります。
set M2TS_ALERT2=もしもうまく行かない場合は、元の動画を別のフォーマットに変換してください
set M2TS_ALERT3=（おまけスクリプトで変換できるかもしれません。使い方.txtを読んでから使用してください。）
set M2TS_ALERT1=ファイルはエンコード中にクラッシュすることがあります
set M2TS_ALERT2=夏蓮根のtool\TEMPフォルダの下に一時ファイルを作って作業します
set M2TS_ALERT3=エンコードが成功したら、ファイルは自動で削除されます
set MV1_ALERT1=Microsoft Video 1は古いコーデックで、画質も劣化してしまうので非推奨です。
set MV1_ALERT2=次からはUt Vodeo Codecをインストールして使うか、無圧縮AVIあたりで出力することを推奨します。
set SIZE_ALERT=元動画の縦横の解像度が4の倍数ではないので失敗するかもしれません。その場合はサイズを修正してください。
set SHUT_CONFIRM=エンコードが終わったら、
set PRETYPES1=この動画はエンコがイマイチなので、プリセットsは使わないほうが良いかもしれません
set PRETYPES2=この動画はビットレートが高めなので、プリセットaとかも試してみることを勧めます
set PRETYPES3=動画エンコなしで、音声のみエンコするプリセットsも試してみると良いかもしれません
set PRETYPES4=元の動画よりビットレートが膨らんでいます

rem shut.batのメッセージ
set SHUT_TITLE=エンコード終了
set SHUT_ALERT=120秒後に全てのアプリケーションを終了後シャットダウンします。
set SHUT_CANCEL=（何かキーを押すとキャンセルします）
set SHUT_CANCEL2=（キャンセルは右上のXを押してください）
set CANCEL_MESSAGE=シャットダウンをキャンセルしました。

rem tool_downloader.batのメッセージ
set DOWNLOADER_TITLE=オートダウンローダー
set DOWNLOADER_ANNOUNCE=ツールをダウンロード・更新します。
set DOWNLOADER_QUESTION1=すべてのツールを全部自動で落とす？（y/n）
set DOWNLOADER_QUESTION2=（自分で手動で落としたい場合はnを）
set NERO_LICENSE1=neroAacEnc.exeを使用するにはライセンスに同意が必要です。
set NERO_LICENSE2=Nero AAC Codec「エンドユーザー使用許諾条項」を開くから
set NERO_LICENSE3=読んだ後戻ってきて下さい！（読んだ後は閉じてもOK）
set NERO_QUESTION=Nero AAC Codecの「エンドユーザー使用許諾条項」に同意しますか？（y/n）
set DOWNLOADER_MANUAL1=以下のサイトからひとつひとつ落として、解凍せずにArchivesフォルダに全部入れて下さい！
set DOWNLOADER_MANUAL2=全部ダウンロードし終わったら、エンターを押してください
set DOWNLOADER_END=完了
set DOWNLOADER_ERROR1=以下のファイルのダウンロードに失敗しました。
set DOWNLOADER_ERROR2=（理由：サーバ移転、ダウンローダ不具合、ネット切断、等）
set DOWNLOADER_ERROR3=きちんとネットに繋がってるかもう一度チェックしてから再起動して下さい。
set DOWNLOADER_ERROR4=それでも駄目だったら、手動でダウンロードしてください
set DOWNLOADED=既にダウンロードされています
set A_ENCODER_SELECT1=音声エンコーダーを選びなさいよね！
set A_ENCODER_SELECT2=1: FDK AAC （自由度高。ダウンロード後に実行ファイルを作成するので、少し時間がかかります。）
set A_ENCODER_SELECT3=2: qaac （iTunesで使われるApple社製エンコーダーを利用。音楽系に。）
set A_ENCODER_SELECT4=3: neroaacenc （以前につんでれんこやAviUtl等でエンコードしていて、実行ファイルを持っている人のみ）
set A_ENCODER_SELECT5=4: ffaac （音質は高くない。追加のインストールが不要なのがメリットか？）
set COREAUDIO_INSTALL1=iTunesおよびQuickTimeがインストールされていないようです
set COREAUDIO_INSTALL2=どちらかを選んでください
set COREAUDIO_INSTALL3=1: iTunes、もしくは、QuickTimeをインストールする
set COREAUDIO_INSTALL4=2: Apple社製エンコーダーと関連ファイルのみを利用する

rem tool_installer.batのメッセージ
set INSTALLER_TITLE=ダウンロードしたツールを解凍、
set INSTALLER_ANNOUNCE=neroAacEnc.exeをtoolフォルダに収納します。
set INSTALLER_ANNOUNCE2=neroAacEnc.exeを使うように設定を書き換えます
set INSTALLER_END=完了
set INSTALLED=既にインストールされています

rem version_check.batのメッセージ
set VER_CHECK_ERROR=バージョンチェック失敗（回線切断orダウンローダ起動失敗orサーバダウン）
set VER_CHECK_NEW1=新しいバージョンが出ています
set VER_CHECK_NEW2=（アップデートの方法はサイトの「つかいかた」を・・・）
set VER_CHECK_LOG=更新内容
set UPDATE_QUESTION1=自動アップデートしますか？（y/n/s）
set UPDATE_QUESTION2=（このままエンコードを続けるならnを選択）
set UPDATE_QUESTION3=（今後もこのバージョンをスキップし続けたいならsを選択）
set UPDATE_QUESTION4=（アップデート後に一旦終了します。お手数ですが、もう一度動画をドロップしてください）
set UPDATE_ERROR=アップデート失敗（回線切断orダウンローダ起動失敗orサーバダウン）
set UPDATE_ANNOUNCE1=アップデート開始～♪
set UPDATE_ANNOUNCE2=アップデート完了～♪
set UPDATE_ANNOUNCE3=次に関連ツールのアップデートをしてから終了します

rem update.batのメッセージ
set INIT_ANNOUNCE2=関連ツール自動アップデート

rem x264_enc.batのメッセージ
set OPTION_SUCCESS=x264オプション設定完了～♪
set X264_ENC_START=動画エンコ開始～♪
set PASS_ERROR=パス数の設定が間違っています。
set PASS_ANNOUNCE1=パス数自動設定モード～♪
set PASS_ANNOUNCE2=１pass目～♪
set PASS_ANNOUNCE3=２pass目～♪
set PASS_ANNOUNCE4=サイズオーバー
set PASS_ANNOUNCE5=３パス目を実行します。
set PASS_ANNOUNCE6=３pass目～♪
set PASS_ANNOUNCE7=強制1passモード～♪
set PASS_ANNOUNCE8=強制2passモード～♪
set PASS_ANNOUNCE9=強制3passモード～♪
set PASS_ANNOUNCE10=CRFモード～♪
set PASS_ANNOUNCE11=目標ビットレートを下げて４パス目を実行します。
set PASS_ANNOUNCE12=４pass目～♪
set X264E_ERROR1=正常にエンコードできませんでした・・・
set X264E_ERROR2=デコーダを変えてみるか、おまけで他のコーデックのaviに変換してから
set X264E_ERROR3=もう一回エンコしてみてください

rem FLV4enc.batのメッセージ
set FLV_ANNOUNCE=FLV作成開始～♪
set VP6VFW_ERROR=vp6vfw.dllが見つかりません。インストール方法は、読んでください.txtをお読みください
set ARATE_ERROR1=FLVを作るには、MP3の音声サンプリングレートが、44100Hzか22000Hzである必要があります
set ARATE_ERROR2=今回のMP3の音声サンプリングレート
set MP3_SIZE_ERROR=MP3のファイルサイズが大きすぎます
set NOT_FLV_ANNOUNCE=今回の条件ではFLVにできません。代わりにMP4を作成します
set MAKE_FLV_ANNOUNCE=静止画なので、MP4ではなくFLVを推奨します。
set FLV_SUCCESS=FLV作成完了～♪

rem ここにD&Dして動画をチェック.batのメッセージ
set UP_CHECK1=：投稿可
set UP_CHECK2=：投稿不可
set CONFIRM_ACCOUNT11=会員
