rem 共通メッセージ
set TDENC_NAME=夏蓮根
set TDENC_NAME2=（つんでれんこ改造版）
set PROCESS_ANNOUNCE=処理中～♪
set MOVIE_FILE_ANNOUNCE=映像ファイル：
set AUDIO_FILE_ANNOUNCE=音声ファイル：
set PAUSE_MESSAGE1=（夏蓮根を終了するわよ！Enterキーを押しなさいよね！）
set PAUSE_MESSAGE2=Enterキーを押しなさいよね！
set HORIZON=------------------------------------------------------------------------------
set HORIZON_B===============================================================================
set USED_SOFTWARE=動画書き出しに使用したソフト：（例：WMM、NiVE）

rem 【ここに動画をD＆D】.batのメッセージ
set TDENC_TITLE=ちょっと！いきなりなによ！こ、心の準備が出来てないじゃない…
set PRESET_ALERT=プリセットのバージョンが古いわよ！
set USER_SETTING1=設定ファイルのバージョンが古いわよ！
set USER_SETTING2=設定ファイルを自動更新する？（y/n）
set USER_SETTING3=を更新するわよ！これまでの設定ファイルは、
set USER_SETTING4=にリネームしとくわ！
set PRESET_ALERT2=手動更新する場合はUSER_VERSIONの修正も忘れないでよね！
set PRESET_ALERT3=（旧バージョンの設定は無視！）
set DOUBLECLICK_ALERT1=このファイルをダブルクリックしても意味ないわよ？
set DOUBLECLICK_ALERT2=つんでれんこまとめwikiの使い方をきちんと読みなさいよね！
set FILENAME_ERROR1=ファイル名かフォルダ名の中にうまく扱えない特殊な文字があるわよ！（ぷんすか
set FILENAME_ERROR2=List2で文字化けしているファイル名かフォルダ名を変えなさいよね！（ぷぷんすか
set FILENAME_ERROR3=上で切れている後の文字が問題よ！！さっさと修正しなさい！（ぷぷんすか
set UNITE_AVI_ANNOUNCE1=分割AVI連結えんこも～ど
set UNITE_AVI_ANNOUNCE2=※インタレ解除・フルレンジ機能などは無効
set ONE_MOVIE_ANNOUNCE=通常えんこも～ど
set SEQUENCE_ANNOUNCE=連続えんこも～ど
set SEQUENCE_ANNOUNCE2=連続テストえんこも～ど
set MOVIE_INFO_ERROR1=動画解析に失敗・・・
set MOVIE_INFO_ERROR2=ユーザー名、フォルダ名、ファイル名に「＝」か全角のスペースが使われてる可能性があるわ
set MOVIE_INFO_ERROR3=　　対処法１：ファイル名から全角のスペースを削除する
set MOVIE_INFO_ERROR4=　　対処法２：一旦動画をドライブ（Cドライブ等）直下に移動する
set SEQUENCE_END1=お、終わったわよ！ほんと乱暴なんだから・・・
set SEQUENCE_END2=どのファイルがどのMP4かきちんとメモしてからウィンドウを閉じなさいよ！
set SEQUENCE_END3=今度からはもっとやさしく扱ってよね・・・/////
set SEQUENCE_END4=個のエンコードできない動画があったわよ！！
set SEQUENCE_END5=そもそも、このパソコンでちゃんと再生できるの？必要なコーデックはインストールした？
set MUX_ANNOUNCE=MUXえんこも～ど
set MUX_ALERT1=.nvvファイルは対応してないわ
set MUX_ALERT2=DirectShow出力でAVIに書き出してから使ってね！
set SWF_ALERT=swfファイルはサポート対象外なの
set SWF_ALERT2=この2つを参考にaviに変換してきなさい！
set NVV_ALERT=nvvファイルはサポート対象外なの。DirectShow出力プラグインでAVIにしてから使ってね
set VIDEO_ENC_ERROR=映像のエンコードに失敗したわ・・・
set AVS_ERROR1=Avisynthのレジストリ登録に失敗・・・ごめんなさい・・・
set AVS_ERROR2=Avisynthを別途インストールしてからもう一度使ってみてね！
set AVS_ERROR3=（Avisynth_258.exe＜http://sorceforge.net/projects/avisynth2/＞を手動インストールしてから使ってみてね）
set BRACKET_ERROR1=動画のファイル名かパスに半角の"("や")"が含まれていると、エンコードできないわよ！リネームしてきなさい！
set PROJECTFILE_ERROR1=ちょっと！これ動画ファイルじゃなくてプロジェクトファイルじゃない！！
set PROJECTFILE_ERROR2=ちゃんとWindowsムービーメーカーで「ムービーの発行」をしてwmvファイルにしてよね！！
set PROJECTFILE_ERROR3=ちゃんとWindows　Liveムービーメーカーで「ムービーの保存」をしてwmvファイルにしてよね！！
set PROJECTFILE_ERROR4=ちゃんとAviUtlで「AVI出力」をしてaviファイルにしてよね！！
set PROJECTFILE_ERROR5=ニコニコムービーメーカーのファイル→動画をアップロードで直接投稿しなさい！！
set PROJECTFILE_ERROR6=AviUtlの拡張編集にドロップしなさいってマニュアルに書いてなかった？！
set PROJECTFILE_ERROR6=紙芝居クリエーターで、ファイル→ムービーファイルの保存をしなさい！！
set PATH_ERROR1=ちょっと！もしかしてPATHの設定がおかしいんじゃない！！
set PATH_ERROR2=次のページを参考に修正してみたら？
set ANTIVIRUS_ERROR1=ちょっと！もしかしてアンチウイルスソフトが必要なファイルを消しているんじゃないの？
set ANTIVIRUS_ERROR2=toolフォルダに7z.exe、7z.dll、curl.exeが無かったら、アンチウイルスソフトの設定を変更しなさい！！
set ANTIVIRUS_ERROR3=それが終わったら、zipを解凍するところからやり直しよ！！いいわね！！
set UNZIP_ERROR1=zipの解凍がおかしいわよ！！解凍方法を変更しなさい！！
set ANTIVIRUS_ERROR4=アンチウィルスソフトが私の邪魔をしてるじゃない！！
set ANTIVIRUS_ERROR5=avs2pipemod、curl、MediaInfo、neroAacEnc、x264とかの実行を許可するように設定変更しなさい！！
set DELTEMP1=ちょっと！前に失敗した時の一時ファイルが一杯残っているじゃない！！
set DELTEMP2=同時に他にエンコさせていないなら片付けちゃうけど、いいわよね？（y/n）
set FILE_DROP1=動画ファイルをこのウィンドウにドロップしなさい！！
set FILE_DROP2=次！！音声ファイルをここにドロップしなさい！！
set FILE_DROP3=（さっきの動画ファイルの音声を使う場合は、もう一回動画をドロップよ！！）
set FILE_DROP4=ドロップしたら、Enterキーを一回だけ押すのよ
set FILE_DROP5=空白や記号が含まれていたら、ちゃんと動かないかも。直して出直してきなさい
set FILENAME_ERROR_MP4=こんなファイル名つけるんじゃないわよ！！MP4
set FOLDER_ALERT1=ちょっと！このフォルダ、書き込みが出来ないじゃない！！
set FOLDER_ALERT2=（Program Files以下など書き込み制限のある場所には、夏蓮根を置かないで下さい）

rem avs.bat、cat.bat、movie.bat、mux.batのメッセージ
set ANALYZE_ANNOUNCE=動画解析中～♪
set ANALYZE_END=動画解析完了～♪
set ANALYZE_ERROR1=動画の解析に失敗・・・
set ANALYZE_ERROR2=での動画の解析に失敗・・・
set ANALYZE_ERROR3=デコーダーを変えてもう一度チャレンジするからそこで待っていなさい！
set ANALYZE_ERROR4=こうなったら、奥の手よ。動画フォーマットを変えてもう一度チャレンジするわよ！いいわよね？（y/n）
set DECODE_ERROR1=動画のデコードに失敗したわ・・・
set DECODE_ERROR2=インデックス処理をしてもう一度チャレンジするからそこで待っていなさい！
set DECODE_ERROR3=正常にデコードできなかったわ・・・
set DECODE_ERROR4=Avisynth_258.exe＜http://sorceforge.net/projects/avisynth2/＞を手動インストールしてから使ってみてね
set DECODE_ERROR5=ダメなら映像や音声の形式を変えて保存してからもう一度使ってみてね
set DECODE_ERROR6=それでもだめだったら・・・ごめんなさい・・・
set VIDEO_ENC_ANNOUNCE=動画のエンコ作業に突入～♪
set AVS_END=映像AVS作成完了～♪
set VIDEO_ENC_END=動画エンコ完了～♪
set SILENCE_ANNOUNCE=無音ファイルを作成～♪
set AUDIO_ENC_ANNOUNCE=音声のエンコ作業に突入～♪
set SKIP_A_ENC_ANNOUNCE=元のAACな音声をそのまま使うわよ！
set WAV_ANNOUNCE=WAVファイル作成中～♪
set MONAURAL=モノラル
set STEREO=ステレオ
set BITRATE_OVER1=元の動画の映像ビットレート
set BITRATE_OVER2=エンコ後の映像ビットレート
set BITRATE_OVER3=元の動画の映像をそのまま使うことにするわよ！！
set BITRATE_OVER4=ちょっとがんばればエコ回避できそうなのでやり直すわよ！！
set AMV_INSTALL1=ちょっと！！AMVビデオコーデックがインストールされていないわよ！！
set AMV_INSTALL2=作者さんのサイトを開いてあげるから、インストールしてやり直しなさいよね！！
set AMV_INSTALL3=（シェアウェアだけど、夏蓮根で使うだけだったら、無料で使えるわ！！）

rem create_mp4.batのメッセージ
set MP4_ANNOUNCE=MP4作成開始～♪
set MP4_ERROR1=エンコードに失敗したわ・・・
set MP4_ERROR2=ごめんなさい・・・
set MP4_ERROR3=上に「requested bitrate is too low. estimated minimum is ??? kbps」と書かれていたら
set MP4_ERROR4=音声ビットレートを下げて、映像ビットレートを??? kbps以上にしてやり直しなさい！！
set MP4_SUCCESS=MP4作成完了～♪
set SIZE_SUCCESS1=動画ファイルの容量のチェック完了～♪
set SIZE_SUCCESS2=容量オーバーしてないわよ♪
set SIZE_ERROR1=よ、容量オーバー・・・ごめんなさい・・・
set SIZE_ERROR2=他のプリセットでさっさとやり直しなさい！！
set DERE_MESSAGE1=完成～♪
set DERE_MESSAGE2=ま、また使ってくれると・・・う、うれしいな・・・（/ω＼）
set AUTO_BR_LIMIT_CHANGE1=どうやら、私には扱いにくい動画がお好みのようね？
set AUTO_BR_LIMIT_CHANGE2=次から、1passを試す基準を6分51秒以下に変更するわよ！！
set AUTO_BR_LIMIT_CHANGE3=次から、1passを試す基準を5分28秒以下に変更するわよ！！
set ECONOMY_SUCCESS=エコノミー回避できているわよ♪
set ECONOMY_ERROR=エコノミー回避に失敗したわ・・・

rem initialize.batのメッセージ
set INIT_TITLE=は、初めてなんだからやさ（ｒｙ
set INIT_ANNOUNCE=起動時の設定

rem m4a_enc.batのメッセージ
set SYNC_ANNOUNCE=音ズレ修正中～♪
set WAV_END=WAVファイル作成完了～♪
set M4A_ENC_ANNOUNCE=音声エンコ開始～♪
set WAV_ERROR=音声が読み込めなかったから無音ファイルを追加するわよ！
set M4A_SUCCESS=音声エンコ完了～♪
set SAMPLERATE_ALERT=ちょっとぉ！サンプリングレートが高すぎじゃない！こっちで勝手に下げとくからね！
set AUDIO_BITRATE_ERROR1=音声エンコに失敗したわ・・・
set AUDIO_BITRATE_ERROR2=方法を変えてもう一度やり直すから、待ってなさい！！

rem setting_question.batのメッセージ
set QUESTION_START1=べっ、別にあんたの好みなんてどうでもいいんだけど、しょうがないから聞いてやるわ
set QUESTION_START2=どんな設定がいいのよ？ 
set QUESTION_START3=（もしも今回の設定を保存したい時は、質問の答え　半角スペース　sと入力しなさいな）
set QUESTION_START4=（どう答えれば？という時は、aを入力しなさい！私が決めてあげるわ！！）
set PRESET_START1=プリセットはどれ？（l～x）
set PRESET_START2=（よく分からない場合はとりあえずaを選べばいいと思うわ）
set PRESET_LIST0=自動設定モード（エンコードに慣れていない人向けプリセット）
set PRESET_LIST1=アニメ・アイマス・MMDなど　速度重視（or 低スペックPC用）
set PRESET_LIST2=アニメ・アイマス・MMDなど　バランス（エンコ速度・画質両立）
set PRESET_LIST3=アニメ・アイマス・MMDなど　画質重視（or 高スペックPC用）
set PRESET_LIST4=実写・PCゲームなど　速度重視（or 低スペックPC用）
set PRESET_LIST5=実写・PCゲームなど　バランス（エンコ速度・画質両立）
set PRESET_LIST6=実写・PCゲームなど　画質重視（or 高スペックPC用）
set PRESET_LIST7=歌ってみたカテゴリなど（音声エンコのみ、高速）
set PRESET_LIST8=ユーザー定義プリセット（カスタマイズ用。デフォでは激重（≠超高画質））
set PRESET_LIST9=YouTube用（リサイズなし＆大容量、高画質にしたい時は1280x720以上で作っておくこと）
set PRESET_LIST10=品質指定（プレアカでの最適ビットレートの見積りに。ファイルサイズ制限無視）
set PRESET_LIST11=音声のみエンコ。動画エンコなし。ファイルサイズ制限なし。高速
set PRESET_MESSAGE1=プリセットsはmp4+wavでしか利用できないわよ！
set PRESET_MESSAGE2=（このままやると%DEFAULT_SIZE_PREMIUM%MBを越えちゃうから、ニコ動には投稿できないわよ）
set RETURN_MESSAGE1=ちょっとぉ！しっかり選びなさいよ！
set PREMIUM_START1=プレミアム会員？（y/n） 
set PREMIUM_START2=（運営に貢いでる人はy、一般会員の人はnよ）
set PREMIUM_START3=YouTubeのアップロード上限解除の設定は済ませてる？（y/n）
set PREMIUM_START4=（よくわからないならnを選びなさいよね）
set PREMIUM_START5=どのくらいのビットレートにすればいいか目安を知りたいの？
set PREMIUM_START6=（よくわからないならmを選びなさいよね）
set PREMIUM_START7=（どうしてもしたいなら、CRFの値を数字で入力すれば指定できるわ）
set PREMIUM_START8=プレミアム会員ならファイルサイズに問題がなかったら、そのまま投稿しても良いわよ？
set CRF_LIST1=軽さ重視
set CRF_LIST2=バランス
set CRF_LIST3=画質重視
set YOUTUBE_SIZE1=このぐらいのファイルサイズなら、そのまま投稿したらどう？
set YOUTUBE_SIZE2=私がエンコしないほうがきれいになると思うけど、それでもエンコする？（y/n）
set YOUTUBE_ERROR1=上限の解除をしていない場合、動画の長さは15分までよ！
set YOUTUBE_ERROR2=動画を短く分割するか、上限解除の設定をしなさいよね！
set ECONOMY_START1=エコ回避するの？（y/n）
set ECONOMY_START2=高画質をお望みならnを
set ECONOMY_START3=（エコ回避すると、低画質になるかもしれないけれど）
set ECONOMY_START4=（一般会員が混雑時間帯に試聴した時の画質・音質劣化を回避できるわ）
set ECONOMY_START5=（主に音を聴いてもらいたい場合以外は、nがオススメ）
set BITRATE_START1=目標ビットレート（音声＋映像）はいくつ？（単位はkbps、入力例：1500）
set BITRATE_START2=※今回の動画で可能な限界ビットレート（音声＋映像）は
set BITRATE_START3=（高いほうが画質が上がるけど、高すぎると重いって言われるかもね！）
set BITRATE_START4=（高くても1000～2000kbpsくらいでいいんじゃないかしら？）
set BITRATE_START5=目標ファイルサイズ
set BITRATE_START6=MB → 目標ビットレート
set BITRATE_START7=（aならおまかせ。0なら最大ビットレートでエンコするわ！）
set BR_MODE_START1=先に品質基準（crf）エンコを試してみる？（y/n,CRF数値）
set BR_MODE_START2=※品質基準エンコを使うことで、適切なビットレートに調整が可能
set BR_MODE_START3=　ビットレートが過剰だったら、画質は変わらないのに重くなるだけよ！
set BR_MODE_START4=　ビットレートが指定した値をオーバーした場合は、自動で無効に切り替わり
set BR_MODE_START5=　自動でビットレート基準エンコードでやり直すわよ
set RETURN_MESSAGE2=ちょっとぉ！きちんと数字（だけ）を入力してよね！
set RETURN_MESSAGE3=ちょっとぉ！ビットレートが高すぎるわよ！
set RETURN_MESSAGE4=きちんとビットレートの限界値より低く設定してよね！
set DECODE_START1=再生負荷を軽くする？（y/n）
set DECODE_START2=（プレアカエンコで動画がカクつく時はyにするとちょっとだけ改善）
set DECODE_START3=（高ビットレートや高解像度はyがお勧め）
set DECODE_START4=（一般アカ用やエコ回避用の時にｙにすると画質が極端に落ちる場合あり）
set DEINT_START1=インターレース解除する？（a/b/d/y/n）
set DEINT_START2=（aは必要かどうか自動判定、yは強制的にする、nは強制的にしない）
set DEINT_START3=（dはfpsを2倍にしつつ、強制的に解除。bはdにするかnにするか自動判定）
set DEINT_START4=（よくわからないならaを選びなさいよね）
set RESIZE_START1=リサイズは？（入力例：y、n、768:432））
set RESIZE_START2=（yは自動、nはリサイズなし、:（半角）で区切って数値入力で直接指定）
set RESIZE_START3=（横のみを指定した時は、アス比を維持するように縦を計算し、リサイズ）
set RESIZE_START4=※高解像度かつ高FPSの場合、動画視聴中にOSを巻き込んで落ちる場合があるわよ！
set RESIZE_START5=　60fpsなどの時はリサイズすることをお勧めするわ！
set RESIZE_START6=一般会員の解像度の上限を越えているじゃない！今回はリサイズなし（n）は無理よ！
set RESIZE_START7=（よくわからない場合はとりあえずyを選べばいいと思うわ）
set AUDIO_START1=音声のビットレートは？（入力例：160）
set AUDIO_START2=（画質重視：32～48、バランス：96～128、音質重視：192～224が目安かな）
set AUDIO_START3=（無音でいいなら0の入力よ！）
set AUDIO_START4=（元動画と同じにしたいならaと入力よ！高すぎたら、%AUTO_A_BITRATE%kbpsにするわよ。）
set AUDIO_START5=（今回は、aは選べないわ。数字を入力してちょうだい）
set AUDIO_START6=※今回の動画での音声ビットレートの最大値は
set AUDIO_START7=※元の動画と同様にエコ回避する場合の最大値は
set AUDIO_START8=※今回の動画で有効なビットレートの最大値は
set AUDIO_START9=（これ以上に上げても、聴き分けられる耳と視聴環境を持つ人は中々いないわよ！）
set AUDIO_START10=元の音声をエンコなしでそのまま使いたいなら、aよ！
set RETURN_MESSAGE5=ちょっとぉ！音声ビットレートが高すぎるわよ！
set RETURN_MESSAGE6=きちんと可能最大総ビットレートより低く設定してよね！
set RETURN_MESSAGE7=ちょっとぉ！きちんと入力してよね！
set RETURN_MESSAGE8=この映像ファイルは一般会員だとプリセットsは使えないわよ！
set RETURN_MESSAGE9=プレミアム会員になるか、プリセットs以外を使ってよね！
set RETURN_MESSAGE10=解像度が一般会員の制限より高いわよ！
set RETURN_MESSAGE11=プレミアム会員になるか、上限以下にリサイズをしなさいよね！
set RETURN_MESSAGE12=この映像ファイルはプリセットsだとエコノミー回避が出来ないわよ！
set RETURN_MESSAGE13=エコノミー回避をあきらめるか、プリセットs以外を使ってよね！
set SYNC_START1=音ズレ処理をする？（入力例：y、n、-20、30）
set SYNC_START2=（yだとズレを差分から自動計算して音声の冒頭をカット。それが嫌ならnを選択）
set SYNC_START3=（数値入力だと数値分だけ調整。負だとカット、正だと無音追加。単位はミリ秒）
set SYNC_START7=（1秒（s, sec） ＝1000ミリ秒（ms, msec））
set SYNC_START4=（よくわからない場合はとりあえずyを選べばいいと思うわ）
set SYNC_START5=（neroAacEnc.exeがないから、今回はyを選べないわ）
set SYNC_START6=（今すぐneroAacEncをダウンロードするなら、dよ）
set GAIN_START1=音量調整する？（入力例：n、5、-5）
set GAIN_START2=（元のままでいいならnよ！）
set GAIN_START3=（単位dB。5dBでもかなり音量が違うと思うわ。上げすぎると音割れするかもね）
set GAIN_START4=（いきなり20dBとか上げて、耳を痛めても知らないわよ！）
set PWCONF_START2=どんな電源操作をしたいの？
set PWCONF_LIST1=シャットダウンするわよ！
set PWCONF_LIST2=再起動するわよ！
set PWCONF_LIST3=ログオフするわよ！
set PWCONF_LIST4=スタンバイするわよ！
set PWCONF_LIST5=休止するわよ！
set PWCONF_LIST6=電源操作やめ！
set CONFIRM_FILENAME=出力ファイル
set CONFIRM_ON=有効
set CONFIRM_OFF=無効
set CONFIRM_PRETYPE=プリセット　
set CONFIRM_CRFTYPE=CRF モード　
set CONFIRM_ACCOUNT1=アカウント　
set CONFIRM_ACCOUNT2=プレミアム
set CONFIRM_ACCOUNT3=一般
set CONFIRM_ACCOUNT4=YouTube（上限解除済み）
set CONFIRM_ACCOUNT5=YouTube（上限あり）
set CONFIRM_PRETYPE=プリセット　
set CONFIRM_ENCTYPE=エコ回避　　
set CONFIRM_DECTYPE=低再生負荷　
set CONFIRM_DEINT1=インタレ解除
set CONFIRM_DEINT2=自動判定（必要ならば解除）→
set CONFIRM_DEINT3=解除する
set CONFIRM_DEINT4=解除不要
set CONFIRM_RESIZE1=リサイズ　　
set CONFIRM_RESIZE2=拡大
set CONFIRM_RESIZE3=縮小
set CONFIRM_SYNC1=音ズレ修正　
set CONFIRM_SYNC2=自動調整
set CONFIRM_SYNC3=手動調整
set CONFIRM_GAIN1=音量調整　　
set CONFIRM_GAIN2=しない
set CONFIRM_VIDEO=映像　　　　
set CONFIRM_CRF=品質基準エンコ
set CONFIRM_BR=ビットレート基準エンコ
set CONFIRM_PRESET_S=エンコせず、元のまま
set CONFIRM_BITRATE1=ビットレート
set CONFIRM_BITRATE2=映像
set CONFIRM_BITRATE3=音声
set CONFIRM_BITRATE4=総合
set UNKNOWN=エンコード後に確認
set YTUPLOAD_BITRATE=YouTubeでサーバーエンコードされた後の最大ビットレート（解像度から判定）
set CONFIRM_LAST1=これでいいのね？（y/n）(もしも、エンコード終了後に電源操作をしたい場合は、pよ！)
set CONFIRM_LAST2=ちょっとぉ！しっかりしなさいよ！今度はきちんと設定してよね！
set CONFIRM_LAST3=全部の動画をこの設定でエンコードするなら、aよ！
set CONFIRM_OUTTYPE=出力ファイル
set MUTE_ALERT1=neroAacEnc.exeがインストールされていないから、無音になるわよ
set MUTE_ALERT2=今すぐ、neroAacEnc.exeをダウンロードする？（y/n）
set MUTE_ALERT3=QuickTimeがインストールされていないから、無音になるわよ
set MUTE_ALERT4=代わりに、neroAacEnc.exeをインストールする？（y/n）
set M2TS_ALERT1=ファイルはエンコ中にクラッシュすることがあるわよ！！
set M2TS_ALERT2=夏蓮根のtool\TEMPフォルダの下に一時ファイルを作って作業するわよ！！
set M2TS_ALERT3=エンコがちゃんとうまくいったら、一時ファイルは削除しておくわ！！
set MV1_ALERT1=Microsoft Video 1は古くて劣化するからお勧めしないわ。仕方ないから今回はやってあげるけど
set MV1_ALERT2=次からはUt Vodeo Codecをインストールして使うか、無圧縮AVIあたりで出力しなさいよね！！
set SIZE_ALERT=ちょっと！！元動画の縦横の解像度が4の倍数じゃないじゃない！！失敗しても知らないわよ！！
set SHUT_CONFIRM=エンコードが終わったら、
set PRETYPES1=ちょっと！！この動画はエンコがイマイチね！プリセットsは使わないほうがいいかも
set PRETYPES2=ちょっと！！この動画、少し重すぎない？プリセットaとかも試してみたら？
set PRETYPES3=動画エンコなしで、音声のみエンコするプリセットsも試してみたら？
set PRETYPES4=ちょっと！！元の動画よりビットレートが膨らんでいるじゃない！！

rem shut.batのメッセージ
set SHUT_TITLE=エンコードが終わったわよ！
set SHUT_ALERT=120秒後に全てのアプリケーションを終了後
set SHUT_CANCEL=（何かキーを押すとキャンセルするわよ！）
set SHUT_CANCEL2=（キャンセルは右上のXを押すこと！）
set CANCEL_MESSAGE=シャットダウンをキャンセルしたわよ！

rem tool_downloader.batのメッセージ
set DOWNLOADER_TITLE=ちょっと！何も準備できてないじゃない。ほら、どきなさいよ！
set DOWNLOADER_ANNOUNCE=ツールをダウンロード・更新するわよ！
set DOWNLOADER_QUESTION1=すべてのツールを全部自動で落とす？（y/n）
set DOWNLOADER_QUESTION2=（自分で手動で落としたい場合はnよ）
set DOWNLOADER_QUESTION3=もう一回自動で落としてみる？（y/n）
set DOWNLOADER_MANUAL1=以下のサイトからひとつひとつ落として、Archivesフォルダに全部入れてよね！
set DOWNLOADER_MANUAL2=全部ダウンロード終わった？終わってから戻ってくるのよ？
set DOWNLOADER_END=まったく世話が焼けるんだから・・・
set DOWNLOADER_ERROR1=以下のファイルのダウンロードに失敗したわ・・・
set DOWNLOADER_ERROR2=(理由：サーバ移転、ダウンローダ不具合、ネット切断、等)
set DOWNLOADER_ERROR3=きちんとネットに繋がってるかもう一度チェックしてから再起動してね！
set DOWNLOADER_ERROR4=それでも駄目だったら、悪いけど手動でダウンロードしてね・・・
set DOWNLOADED=なによ！もうダウンロードしてあるじゃない！
set A_ENCODER_SELECT1=音声エンコーダーを選びなさいよね！
set A_ENCODER_SELECT2=FDK AAC （自由度高。ダウンロード後に実行ファイルを作成するので、少し時間がかかります。）
set A_ENCODER_SELECT3=qaac （iTunesで使われるApple社製エンコーダーを利用。音楽系に。）
set A_ENCODER_SELECT4=neroaacenc （以前につんでれんこやAviUtl等でエンコードしていて、実行ファイルを持っている人のみ）
set A_ENCODER_SELECT5=ffaac （音質はイマイチ。追加のインストールが不要なのがメリットか？）
set COREAUDIO_INSTALL1=qaacを利用するには、iTunesやQuicktimeに同梱されているApple製のソフトが必要よ！
set COREAUDIO_INSTALL2=iTunesのダウンロードページを開く？（y/n）
set COREAUDIO_INSTALL3=ダウンロードとインストールが終わったら、ENTERを押しなさい！
set COREAUDIO_INSTALL4=ちょっと！インストールしてないじゃない！仕方ないから、必要最低限のファイルだけ用意してあげるわ！
set NERO_LICENSE1=neroAacEnc.exeを使用するにはライセンスに同意が必要よ！
set NERO_LICENSE2=Nero AAC Codecの「エンドユーザー使用許諾条項」を開くから
set NERO_LICENSE3=読んだ後戻ってきてね！（読んだ後は閉じてもいいわよ）
set NERO_QUESTION=Nero AAC Codecの「エンドユーザー使用許諾条項」に同意する？（y/n）
set NERO_INSTALL1=toolフォルダにneroAacEnc^(.exe^)をコピーしたら、ENTERを押しなさい！
set NERO_INSTALL2=（持ってないなら、nで選び直しなさいよね！）
set NERO_INSTALL3=見当らないわよ？もう一回確認しなさい！
set FDKAAC_BUILD_FAIL1=fdkaac.exeの作製に失敗したみたい・・・
set FDKAAC_BUILD_FAIL2=ごめんなさい・・・
set FDKAAC_BUILD_FAIL3=他の音声エンコーダーを選んでみて

rem tool_installer.batのメッセージ
set INSTALLER_TITLE=ツールを入れ・・・る・・・・・なんて事いわせるのよ！このド変態！
set INSTALLER_ANNOUNCE=ツールをtoolフォルダに入れるわよ！
set INSTALLER_END=まったく世話が焼けるんだから・・・
set INSTALLED=ちょっと！もうインストールしてあるわよ

rem version_check.batのメッセージ
set VER_CHECK_ERROR=バージョンチェック失敗（回線切断orダウンローダ起動失敗orサーバダウン）
set VER_CHECK_NEW1=新しいバージョンが出てるわよ！
set VER_CHECK_NEW2=（アップデートの方法はサイトの「つかいかた」をきちんと読むこと！）
set VER_CHECK_LOG=更新内容
set UPDATE_QUESTION1=自動アップデートする？（y/n/s）
set UPDATE_QUESTION2=（このままエンコードを続けるならnを選択よ）
set UPDATE_QUESTION3=（今後もこのバージョンをスキップし続けたいならsを選択よ）
set UPDATE_QUESTION4=（アップデート後に一旦終了するわよ！終わったら、もう一回動画をドロップしなさい！）
set UPDATE_ERROR=アップデート失敗（回線切断orダウンローダ起動失敗orサーバダウン）
set UPDATE_ANNOUNCE1=アップデート開始～♪
set UPDATE_ANNOUNCE2=アップデート完了～♪
set UPDATE_ANNOUNCE3=次に関連ツールのアップデートをしてから終了するわよ！

rem update.batのメッセージ
set INIT_ANNOUNCE2=関連ツール自動アップデート

rem x264_enc.batのメッセージ
set OPTION_SUCCESS=x264オプション設定完了～♪
set X264_ENC_START=動画エンコ開始～♪
set PASS_ERROR=パス数の設定が間違ってるわよ！
set PASS_ANNOUNCE1=パス数自動設定モード～♪
set PASS_ANNOUNCE2=１pass目～♪
set PASS_ANNOUNCE3=２pass目～♪
set PASS_ANNOUNCE4=こ、こんなに大きいなんて聞いてないわよ・・・////（容量的な意味で
set PASS_ANNOUNCE5=も、もう１回ヤったら収まってくれるかしら？////（３pass的な意味で
set PASS_ANNOUNCE6=３pass目～♪
set PASS_ANNOUNCE7=強制1passモード～♪
set PASS_ANNOUNCE8=強制2passモード～♪
set PASS_ANNOUNCE9=強制3passモード～♪
set PASS_ANNOUNCE10=CRFモード～♪
set PASS_ANNOUNCE11=も、もう、しつこいわねぇ。これで最後だからね！！////（４pass的な意味で
set PASS_ANNOUNCE12=４pass目～♪
set X264E_ERROR1=正常にエンコードできなかったわ・・・
set X264E_ERROR2=デコーダを変えてみるか、おまけで他のコーデックのaviに変換してから
set X264E_ERROR3=もう一回エンコしてみなさい！！

rem FLV4enc.batのメッセージ
set FLV_ANNOUNCE=FLV作成開始～♪
set VP6VFW_ERROR=vp6vfw.dllが見つからないわ。インストール方法は、読んでください.txtに書いておいたわ
set ARATE_ERROR1=FLVを作るには、MP3の音声サンプリングレートが、44100Hzか22000Hzじゃないとダメよ
set ARATE_ERROR2=今回のMP3の音声サンプリングレート
set MP3_SIZE_ERROR=MP3のファイルサイズが大きすぎるわ
set NOT_FLV_ANNOUNCE=これだとFLVにするとダメね。MP4を作ることにするわ。いいわよね？
set MAKE_FLV_ANNOUNCE=静止画だったら、MP4じゃなくてFLVがお勧めよ。ちゃんと作れそうだし、いいわよね？
set FLV_SUCCESS=FLV作成完了～♪

rem ここにD&Dして動画をチェック.batのメッセージ
set UP_CHECK1=：投稿可。
set UP_CHECK2=：投稿不可。
set CONFIRM_ACCOUNT11=会員
